enum HomeAction {
  OVERVIEW_INFO = '@home/UPDATE_INFO',
  UPDATE_OVERVIEW = '@home/UPDATE_OVERVIEW',
  UPDATE_OVERVIEW_ON_BOARDING = '@home/UPDATE_OVERVIEW_ON_BOARDING',
  UPDATE_SOLD_HOUSE_ON_BOARDING = '@home/UPDATE_SOLD_HOUSE_ON_BOARDING',
  GET_TOP_AREAS = '@home/GET_TOP_AREAS',
  UPDATE_COMPARE_AREA = '@home/UPDATE_COMPARE_AREA',
  GET_USER_AGENT = '@home/GET_USER_AGENT',
  UPDATE_USER_AGENT = '@home/UPDATE_USER_AGENT',
  UPDATE_DOMAIN_WEBSITE = '@home/UPDATE_DOMAIN_WEBSITE',
  UPDATE_LIST_AGENT = '@home/UPDATE_LIST_AGENT',
  IS_REFRESHED = '@home/IS_REFRESHED',
  GET_DATA_ONBOARDING = '@home/GET_DATA_ONBOARDING',
}
export default HomeAction;
