enum AppAction {
	RUN_AUTHENTICATED_FLOW = '@auth/RUN_AUTHENTICATED_FLOW',
	UPDATE_MY_PROFILE = '@auth/UPDATE_MY_PROFILE',
	FETCH_DATA = 'FETCH_DATA',
	FETCH_ORDER = 'FETCH_ORDER',
	CANCEL_ORDER = 'CANCEL_ORDER',
	FETCH_ALL_DATA = 'FETCH_ALL_DATA',
	CREATE_ORDER = 'CREATE_ORDER',
}

export default AppAction;
