enum AppAction {
	RUN_AUTHENTICATED_FLOW = '@auth/RUN_AUTHENTICATED_FLOW',
	UPDATE_MY_PROFILE = '@auth/UPDATE_MY_PROFILE',
	FETCH_DATA = 'FETCH_DATA',
	FETCH_ORDER = 'FETCH_ORDER',
	CANCEL_ORDER = 'CANCEL_ORDER',
}

export default AppAction;
