const RoutePaths = {
	LOGIN: '/auth/login',
	DASHBOARD: '/',
	VERIFY_ACCOUNT: '/verify',
	LOGOUT: '/auth/logout',
	SETTINGS: '/settings',
	NOT_FOUND: '/404',
	CAMPAIGNS: '/campaigns',
	TERMS_AND_CONDITIONS: '/terms-and-conditions',
	PRIVACY_POLICY: '/privacy-policy',
	REGISTER: '/register',
	SETUP_MANAGER: '/setup-manager',
	DETAIL_DOWNSIZES: '/detail-downsizes',
	DETAIL_DOWNSIZES_LATTER: '/detail-downsizes-letter',
	TEMPLATE_1: '/templates-1',
	TEMPLATE_2: '/templates-2',
	TEMPLATE_3: '/templates-3',
	TEMPLATE_4: '/templates-4',
	HOME_BUYER: '/home-buyer',
	HOME_SELLERS: '/home-sellers',
	ABSENTEE_HOMEOWNER: '/absentee-homeowner',
	HOME_UPGRADE: '/home-upgrade',
	MY_REPORT: '/my-report',
	AGENT_REPORT_DYNAMIC: 'agent-report',
	MY_REPORT_DYNAMIC: 'my-report',
	PROSPECT_LOOKUP: '/prospect-lookup',
	MAILING_LISTS: '/mailing-lists',
	MY_NFTS: '/my-nfts',
	CAMPAIGN_NFT_DETAIL: '/campaign-nft-detail',
	MINT_CAMPAIGN_NFT: '/mint-campaign-nft',
	MAILING_LISTS_CREATE: '/mailing-lists/create',
	HOME: '/home',
};
export default RoutePaths;
