enum AppAction {
	APP_LOADING = '@app/APP_LOADING',
	RESET_ROOT_STATE = '@app/RESET_ROOT_STATE',
	SET_THEME = '@app/SET_THEME',
	VISIBLE_MODAL_ADD_MAILING = '@app/VISIBLE_MODAL_ADD_MAILLING',
	VISIBLE_MODAL_BUTTON_ADD_MAILING = '@app/VISIBLE_MODAL_BUTTON_ADD_MAILING',
	VISIBLE_PAYMENT_FORM = '@app/VISIBLE_PAYMENT_FORM',
	VISIBLE_CONFIRM_CAMPAIGN_MODAL = '@app/VISIBLE_CONFIRM_CAMPAIGN_MODAL',
	VISIBLE_RECIPIENTS_MODAL = '@app/VISIBLE_RECIPIENTS_MODAL',
}

export default AppAction;
