enum MailingAction {
  LIST_MAILING_LIST = '@mailing/LIST_MAILING_LIST',
  LIST_MAILING_LIST_SUCCESS = '@mailing/LIST_MAILING_LIST_SUCCESS',

  UPDATE_MAILING_LIST = '@mailing/UPDATE_MAILING_LIST',
  UPDATE_MAILING_LIST_SUCCESS = '@mailing/UPDATE_MAILING_LIST_SUCCESS',

  DELETE_MAILING_LIST = '@mailing/DELETE_MAILING_LIST',
  DELETE_MAILING_LIST_SUCCESS = '@mailing/DELETE_MAILING_LIST_SUCCESS',
}

export default MailingAction;
