enum UserAction {
  UPDATE_PUBLIC_PROFILE = '@user/UPDATE_PUBLIC_PROFILE',
  USER_ASSETS = '@user/USER_ASSETS',
  CAMPAIGN_ASSETS = '@user/CAMPAIGN_ASSETS',
  AGENT_PAST_ORDERS = '@user/AGENT_PAST_ORDERS',
  ADD_NEW_ORDER = '@user/ADD_NEW_ORDER',
  GET_LIST_MEMBERS_SEARCH = '@user/GET_LIST_MEMBERS_SEARCH',
  GET_LIST_MEMBERS_SEARCH_FILE = '@user/GET_LIST_MEMBERS_SEARCH_FILE',
  IS_AGENTLOOKUP = '@user/IS_AGENTLOOKUP',
  IS_SKIPSETUP = '@user/IS_SKIPSETUP',
  IS_PROSPECT_LOOKUP = '@user/IS_PROSPECT_LOOKUP',
  SAVE_CARD_LIST = '@user/SAVE_CARD_LIST',
}

export default UserAction;
