enum AppAction {
  //doc action
  RUN_AUTHENTICATED_FLOW = '@auth/RUN_AUTHENTICATED_FLOW',
  UPDATE_MY_PROFILE = '@auth/UPDATE_MY_PROFILE',
  RESET_ROOT_STATE = '@app/RESET_ROOT_STATE',

  FETCH_DOCUMENT = 'FETCH_DOCUMENT',
  FETCH_LIST_CART = 'FETCH_LIST_CART',
  FETCH_ORDER = 'FETCH_ORDER',
  CANCEL_ORDER = 'CANCEL_ORDER',
  CREATE_ORDER = 'CREATE_ORDER',
  FETCH_ALL_DATA = 'FETCH_ALL_DATA',
  //==============================
  //Course action
  FETCH_COURSE = 'FETCH_COURSE',
}

export default AppAction;
